RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
RuntimeWarning:/home/tractor/.local/lib/python3.8/site-packages/shapely/set_operations.py:133:invalid value encountered in intersection
